name: MLflow CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2  # Gunakan v2 jika v4 bermasalah

    - name: Set up Python 3.10
      uses: actions/setup-python@v2  # Gunakan v2 jika v5 bermasalah
      with:
        python-version: '3.10'

    - name: Check Env
      run: |
        python --version
        pip --version
        uname -a
        pwd
        ls -la

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install mlflow pandas scikit-learn matplotlib seaborn  # Pastikan dependensi sesuai

    - name: Set MLflow Tracking URI
      run: |
        echo "MLFLOW_TRACKING_URI=file:$PWD/mlruns" >> $GITHUB_ENV

    - name: Run MLflow Project
      run: |
        python -m mlflow run ./MLProject --env-manager=local

    - name: List mlruns folder content
      run: ls -la mlruns  # Verifikasi isi mlruns

    - name: Upload MLflow Artifacts
      uses: actions/upload-artifact@v3  # Menggunakan v3 atau versi terbaru yang tidak deprecated
      with:
        name: mlflow-artifacts
        path: mlruns  # Menyimpan seluruh isi folder mlruns sebagai artefak
